---
# tasks file for mariadb-Debian
# Actualizar caché de los paquetes
- name: Actualizar caché de los repositorios
  apt:
      name: '*'
      state: latest
      update_cache: true

# Instalar MariaDB
- name: Instalación MariaDB
  apt:
      name:
          - mariadb-server
          - python3
          - python3-mysqldb
          - ufw
      state: latest

# Iniciar servicio MariaDB
 - name: Iniciar servicio MariaDB
   service:
      name: mariadb
      enabled: true
      state: started

# Reiniciar el servicio de MariaDB
# - name: Reiniciar servicio MariaDB
#  service:
#      name: mariadb
#      state: restarted

# Secure_installation y cambio de contraseña usuraio root
- name: Mysql-secure-installation
  shell:
      echo -e "\nn\nY\nViewnext\nViewnext\nY\nn\nY\nY\n" | sudo mysql_secure_installation
  args:
      executable: /bin/bash

# Importar configuración MariaDB
- name: Establecer configuración
  template:
      src: /etc/ansible/recursos/mariadb/50-server-debian.cnf
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf
      owner: root
      group: root
      mode: '0755'

# Reiniciar Mariadb y aplicar cambios
- name: Aplicar cambios en MariaDB
  service:
      name: mariadb
      enabled: true
      state: restarted

# Creación de la base de datos de wordpress
- name: crear base de datos
  mysql_db:
      name: wordpress
      login_user: root
      login_password: Viewnext
      state: present

# Creación usuario para la base de datos
- name: Crear usuario para la base de datos de wordpress
  mysql_user:
      login_user: root
      login_password: Viewnext
      name: vagrant
      password: Viewnext
      priv: 'wordpress.*:ALL,GRANT'
      host: '%'
      state: present

# Crear archivo SQL
# - name: Crear el archivo SQL
#   copy:
#       content:
#         USE wordpress;
#         UPDATE wp_options SET option_value='http://192.168.10.45' WHERE option_name='siteurl'
#         OR option_name='home';
#       dest: /tmp/commands.slq

# Ejecutar comandos SQL
# - name: Ejecutar comandos sql
#  mysql_db:
#      login_user: root
#      login_password: Viewnext
#      name: wordpress
#      target: /tmp/commands
#  vars:
#      ansible_python_interpreter: /usr/bin/python3

# Habilitar MariaDB en Firewall
- name: Habilitar servicio mariadb en firewall
  ufw:
      state: enabled

# Abrir puerto 3306 en firewall para conexión remota
- name: Abrir puerto 3306
  ufw:
      rule: allow
      port: 3306

# Habilitar puerto 22
- name: Habilitar puerto 22
  ufw:
      rule: allow
      port: 22

# Reiniciar servicio firewall
- name: Reiniciar servicio firewall
  ufw:
      state: reloaded
