---
# tasks file for apache-RedHat
# Instalar servicio apache
- name: Instalar apache
  yum:
        name: httpd
        state: latest

# Iniciar servicio httpd
- name: Iniciar servicio httpd
  service:
        name: httpd
        state: started
        enabled: true

# Abrir puertos del firewall
- name: Abrir puertos en firewall
  firewalld:
        service: http
        permanent: true
        state: enabled

# Reiniciar firewall
- name: Reiniciar firewall y cargar cambios
  service:
        name: firewalld
        state: reloaded

# Reiniciar httpd
- name: Reiniciar httpd
  service:
        name: httpd
        state: restarted
