---
# tasks file for php-Debian
# Actualizar caché de los paquetes
- name: Actualizar caché paquetes
  apt:
        name: '*'
        state: latest
        update_cache: true

# Instalar paquetes necesarios
- name: Instalar paquetes requeridos
  apt:
        name:
            - php
            - php-gd
            - php-xml
            - php-mbstring
            - php-mysql
        state: latest
          
# Reiniciar módulo php-fpm
- name: Reiniciar módulo php.fpm
  service:
        name: php-fpm
        state: restarted
  when: ansible_facts['services']['php-fpm'] is defined

# Abrir puerto para srvicio http
# - name: Abrir puerto par servicio http
#  ufw:
#        service: http
#        permanent: true
#        state: enabled

# Riniciar servicio Firewall
# - name: Reiniciar ufw
#  ufw:
#        state: reloaded
#
# Descargar Archivos Wordpress
- name: Descargar wordpress
  get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

# Descomprimir archivo de wordpress
- name: Extraer archivos de wordpress
  unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html"
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'

# Estabalcer configuración wp-config.php
- name: Establecer configuración wp-config.php
  template:
    src: /etc/ansible/recursos/wordpress/wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0755'

# Estabecer conf
- name: Importar archivo wordpress.conf(proxy)
  template:
          src: /etc/ansible/recursos/wordpress/000-default.conf.j2
          dest: /etc/apache2/sites-available/000-default.conf
          owner: root
          group: root
          mode: '0644'

# Reiniciar servicio Apache Web Server
- name: Reiniciar Apache Web Server
  become: yes
  service:
        name: apache2
        state: restarted

# Reiniciar servidor
- name: Reiniciar servidor remoto
  reboot:
        reboot_timeout: 30
        post_reboot_delay: 30


