# Instalación completa de wordpress

- name: Instalación de MariaDB
  hosts: mariadb
  become: yes
  become_method: sudo
  tasks:
  - name: Incluir role
    ansible.builtin.include_role:
      name: "mariadb-{{ ansible_os_family }}"

- name: Implantación copia de seguridad en MariaDB
  hosts: mariadb
  become: yes
  become_method: sudo
  tasks:
  - name: Incluir role
    ansible.builtin.include_role:
      name: backup

- name: Instalación de Apache
  hosts: Apache
  become: yes
  become_method: sudo
  tasks: 
  - name: Incluir role
    ansible.builtin.include_role: 
      name: "apache-{{ ansible_os_family }}"

- name: Instalación de php y wordpress
  hosts: Apache
  become: yes
  become_method: sudo
  tasks: 
    - name: Incluir role
      ansible.builtin.include_role:
        name: "php-{{ ansible_os_family }}"
